import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F4EF',
  },
  screenContent: {
    padding: 20,
    paddingBottom: 48,
  },
  heroCard: {
    backgroundColor: '#111827',
    borderRadius: 28,
    padding: 26,
    marginBottom: 22,
  },
  logo: {
    color: '#FBBF24',
    fontSize: 46,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 16,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 10,
  },
  heroText: {
    color: '#D1D5DB',
    fontSize: 16,
    lineHeight: 23,
  },
  header: {
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#111827',
    letterSpacing: 0,
  },
  headerSubtitle: {
    marginTop: 4,
    color: '#6B7280',
    fontSize: 15,
    lineHeight: 21,
  },
  section: {
    marginBottom: 22,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 10,
    color: '#111827',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  cardSoft: {
    backgroundColor: '#FFFBEB',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  cardTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  bodyText: {
    color: '#374151',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 8,
  },
  smallNote: {
    color: '#6B7280',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  inputGroup: {
    marginBottom: 14,
  },
  label: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: '#111827',
  },
  textArea: {
    minHeight: 110,
  },
  primaryButton: {
    backgroundColor: '#111827',
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderRadius: 16,
    marginBottom: 10,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
  },
  secondaryButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 16,
    marginBottom: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  secondaryButtonText: {
    color: '#111827',
    fontWeight: '800',
    fontSize: 15,
  },
  smallButton: {
    backgroundColor: '#111827',
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 16,
    flex: 1,
    alignItems: 'center',
  },
  smallButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 4,
    marginBottom: 6,
  },
  tag: {
    backgroundColor: '#EEF2FF',
    color: '#3730A3',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '800',
  },
  statusPill: {
    backgroundColor: '#ECFDF5',
    color: '#047857',
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: '900',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  rowGap: {
    flexDirection: 'row',
    gap: 10,
  },
  buttonGap: {
    marginTop: 6,
  },
  emptyState: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  emptyText: {
    color: '#6B7280',
    fontSize: 15,
    lineHeight: 22,
  },
  messageList: {
    marginBottom: 12,
  },
  messageBubble: {
    padding: 14,
    borderRadius: 18,
    marginBottom: 10,
    maxWidth: '90%',
  },
  mine: {
    alignSelf: 'flex-end',
    backgroundColor: '#DCFCE7',
  },
  theirs: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  messageText: {
    color: '#111827',
    fontSize: 15,
    lineHeight: 21,
  },
  messageMeta: {
    color: '#6B7280',
    fontSize: 11,
    marginTop: 6,
  },
});
